apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml

patches:
  - target:
      kind: Deployment
      name: my-deployment
  patch: |-
    - op: replace
      path: /spec/template/metadata/labels/app
      value: updated-app-label

